<div id="prod" class="discount">
    <h2><?php echo $this->__('Custom Codes') ?></h2>
    <div  class="discount-form">
        <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
        <div class="input-box">
            <input type="text" name="code" id="custom_code"/>
        </div>
        <div class="buttons-set">
            <button class="button" name="submit" onclick="check()"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
        </div>
    </div>
</div>





<script >
    //<![CDATA[
    function check() {

        var data = jQuery("#custom_code").val();
                jQuery.ajax({
                    type: 'post',
                    url: '<?php echo Mage::getUrl('custom/index/save')?>',
                    data: {data: data},
                    cache: false,
                    error: function () {
                        alert('Smth went wrong');
                    },
                    complete: function (data) {
                        var datas = data.responseText.evalJSON();
                        jQuery('#prod').replaceWith(datas);
                    }
                });

            }
    //]]>
</script>

